### ISSUE TITLE
[Bug] Empty lists are encoded as list with one null

### ISSUE THREAD

**Issue by akshaymankar** [clovyr/aeson-yaml#2]
Example:

This code:
```haskell
Data.Aeson.Yaml.encode (object ["foo" .= ([] :: [Int])])
```

would make a YAML which looks like this:
```yaml
foo:
  -
```

It should be like this:

```yaml
foo: []
```

**Comment by patrickmn** [comment]
Thank you. Fixed in https://github.com/clovyr/aeson-yaml/commit/ceb8d53e1a84cb07447c651762f83405673127ea and released as aeson-yaml 1.0.3.0.
